#!/usr/bin/env python3
"""Scaffold a new question pack under docs/questions."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
from textwrap import dedent

ROOT = Path(__file__).resolve().parents[1]
QUESTION_DIR = ROOT / "docs" / "questions"

TEMPLATE_QUESTION = {
    "question": "Replace this with a clear, exam-style prompt.",
    "choices": [
        "Answer A",
        "Answer B",
        "Answer C",
        "Answer D",
    ],
    "answer": "Answer A",
    "explanation": "Explain why the correct choice is right (and the others aren't).",
    "tags": ["sample-domain"],
}


def slugify(value: str) -> str:
    slug = "".join(char.lower() if char.isalnum() else "-" for char in value.strip())
    while "--" in slug:
        slug = slug.replace("--", "-")
    return slug.strip("-") or "new-pack"


def build_metadata(track_key: str, title: str, description: str | None) -> str:
    meta = dedent(
        f"""\
        // Track Key: {track_key}
        // Title: {title}
        // Description: {description or 'Describe the exam domain here.'}
        // Generated by scripts/create_question_pack.py

        """
    )
    return meta


def create_pack(filename: Path, title: str, description: str | None, force: bool) -> Path:
    if filename.exists() and not force:
        raise FileExistsError(f"{filename} already exists. Use --force to overwrite.")
    payload = [TEMPLATE_QUESTION]
    metadata = build_metadata(filename.stem, title, description)
    filename.write_text(metadata + json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return filename


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a question pack template.")
    parser.add_argument("track", help="Slug/key for the track (used as the file name).")
    parser.add_argument("--title", help="Human-friendly track title.", default="New Track")
    parser.add_argument(
        "--description",
        help="One-line description for README/UI summaries.",
        default=None,
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite the file if it already exists.",
    )
    args = parser.parse_args()

    QUESTION_DIR.mkdir(parents=True, exist_ok=True)
    slug = slugify(args.track)
    path = QUESTION_DIR / f"{slug}.json"
    create_pack(path, args.title or slug, args.description, args.force)
    print(f"Created template: {path.relative_to(ROOT)}")
    print("Next steps:")
    print("  1. Replace the sample question with real content.")
    print("  2. Run `make check` to validate the pack before committing.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
